import { ScrollView, Text, View, TextInput, TouchableOpacity, Alert } from "react-native";
import { useState } from "react";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function ClinicalSummaryScreen() {
  const router = useRouter();
  const colors = useColors();
  const [visitNotes, setVisitNotes] = useState("");
  const [summary, setSummary] = useState("");

  const generateSummary = () => {
    if (!visitNotes.trim()) {
      Alert.alert("Error", "Please enter visit notes");
      return;
    }

    // Mock AI summary
    setSummary(`AI-Generated Clinical Summary:

Patient presented with ${visitNotes.substring(0, 50)}...

Key Findings:
- Vital signs within normal limits
- Physical exam unremarkable
- Diagnosis: Upper respiratory infection

Plan:
- Supportive care
- Follow up in 1 week if symptoms persist

This summary was generated by AI. Please review and confirm accuracy.`);
  };

  return (
    <ScreenContainer className="bg-background">
      <ScrollView contentContainerStyle={{ flexGrow: 1 }} className="flex-1">
        <View className="p-6 gap-6">
          <View className="gap-2">
            <Text className="text-2xl font-bold text-foreground">AI Clinical Summary</Text>
            <Text className="text-sm text-muted">Generate automated visit summaries</Text>
          </View>

          <View className="bg-surface rounded-xl border border-border p-4 gap-4">
            <View className="gap-2">
              <Text className="text-sm font-semibold text-foreground">Visit Notes</Text>
              <TextInput
                className="bg-background border border-border rounded-lg p-3 text-foreground"
                placeholder="Enter clinical notes from the visit..."
                placeholderTextColor={colors.muted}
                value={visitNotes}
                onChangeText={setVisitNotes}
                multiline
                numberOfLines={6}
              />
            </View>

            <TouchableOpacity
              className="bg-primary rounded-lg p-4 items-center active:opacity-80"
              onPress={generateSummary}
            >
              <Text className="text-white font-semibold">Generate Summary</Text>
            </TouchableOpacity>
          </View>

          {summary ? (
            <View className="bg-surface rounded-xl border border-border p-4 gap-2">
              <Text className="text-sm font-semibold text-foreground">Generated Summary</Text>
              <Text className="text-sm text-muted">{summary}</Text>
            </View>
          ) : null}

          <TouchableOpacity
            className="bg-surface border border-border rounded-lg p-4 items-center active:opacity-80"
            onPress={() => router.back()}
          >
            <Text className="text-foreground font-semibold">Back to Tools</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}
